# Generated by Django 6.0.1 on 2026-01-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.CharField(choices=[('MED', 'Consulta médica'), ('FER', 'Férias'), ('CUR', 'Curso'), ('FOL', 'Folga'), ('OUT', 'Outro')], max_length=3)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='data_fim_maior_ou_igual_inicio')],
            },
        ),
    ]
