# Generated by Django 6.0.1 on 2026-01-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOR', 'Normal'), ('SOB', 'Sobreaviso')], default='NOR', max_length=3)),
                ('data_inicio', models.DateField(help_text='Segunda-feira')),
                ('data_fim', models.DateField(help_text='Domingo')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RASC', 'Rascunho'), ('PUB', 'Publicada'), ('ENC', 'Encerrada')], default='RASC', max_length=4)),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_criadas', to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='projetos.secao')),
            ],
        ),
        migrations.CreateModel(
            name='DiaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_dia', models.CharField(choices=[('PRETA', 'Dia útil'), ('AMARELA', 'Sexta-feira'), ('VERMELHA', 'Não útil / Sobreaviso')], max_length=10)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='escalas.escala')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('MAD', 'Madrugada'), ('NOT', 'Noturno'), ('SOB', 'Sobreaviso')], max_length=3)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='escalas.diaescala')),
            ],
        ),
        migrations.CreateModel(
            name='AlocacaoEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TIT', 'Titular'), ('RES', 'Reserva'), ('SOB', 'Sobreaviso')], max_length=3)),
                ('virou_titular', models.BooleanField(default=False)),
                ('foi_acionado', models.BooleanField(default=False, help_text='Indica se o militar foi acionado no dia não útil')),
                ('substituiu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituido_por', to='escalas.alocacaoescala')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='escalas.turnoescala')),
            ],
        ),
        migrations.AddConstraint(
            model_name='escala',
            constraint=models.UniqueConstraint(fields=('secao', 'data_inicio'), name='escala_unica_por_secao_semana'),
        ),
        migrations.AddConstraint(
            model_name='diaescala',
            constraint=models.UniqueConstraint(fields=('escala', 'data'), name='dia_unico_por_escala'),
        ),
        migrations.AddConstraint(
            model_name='turnoescala',
            constraint=models.UniqueConstraint(fields=('dia', 'turno'), name='turno_unico_por_dia'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoescala',
            constraint=models.UniqueConstraint(fields=('turno', 'usuario'), name='usuario_unico_por_turno'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoescala',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'RES')), fields=('turno',), name='um_reserva_por_turno'),
        ),
    ]
