# Generated by Django 6.0.1 on 2026-01-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escalas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DIRETA', 'Troca direta entre operadores'), ('PEDIDO', 'Pedido ao escalante')], max_length=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('alocacao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permutas_destino', to='escalas.alocacaoescala')),
                ('alocacao_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permutas_origem', to='escalas.alocacaoescala')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permutas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
