# Generated by Django 6.0.1 on 2026-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, help_text='Usuário precisa trocar a senha no primeiro login'),
        ),
    ]
