# Generated by Django 6.0.1 on 2026-01-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escalas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='escalas.alocacaoescala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('alocacao',), name='pontuacao_unica_por_alocacao')],
            },
        ),
    ]
